remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
github:
  is_project_page: false
title: The Hobbit (Miniseries)
description: 1080p Full HD | 7.1 Surround English | 5.1 Surround Spanish | Blu-ray available
icon: ./img/artwork/icon.png
author: Chad Heisenberg
