remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
github:
  is_project_page: false
title: The Hobbit (Miniseries)
description: A Chad Heisenberg Fanedit
author: Chad Heisenberg
