remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
title: The Hobbit (Miniseries)
author: Chad Heisenberg
description: An 11 episodes Miniseries fanedit from The Hobbit Trilogy.
